import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  // Absolute base. This repo is a user/org GitHub Pages repo
  // ("<user>.github.io"), always served at the domain root, so "/"
  // resolves correctly everywhere -- including the pre-rendered
  // /faq/index.html and /magazine/index.html shells generated by
  // scripts/generate-static-routes.mjs, where a relative "./" base would
  // incorrectly resolve one level too deep. Routing uses BrowserRouter
  // (clean paths, no "/#/") combined with the GitHub Pages SPA-fallback
  // trick in public/404.html + index.html -- see those two files for how
  // deep links survive a refresh without server-side rewrite support.
  base: '/',
  plugins: [react()],
})
