import { useEffect } from "react";
import siteConfig from "./routes.json";

export interface SEOOptions {
  /** Route path, e.g. "/faq". Used to look up canonical + defaults and to
   * build the canonical/OG URL. */
  path: string;
  /** Overrides the title from routes.json if provided. */
  title?: string;
  /** Overrides the description from routes.json if provided. */
  description?: string;
  /** Extra JSON-LD objects to inject alongside the default WebSite graph
   * (e.g. FAQPage, BreadcrumbList). */
  structuredData?: Record<string, unknown>[];
}

const SITE_URL = siteConfig.siteUrl;

function setMeta(attr: "name" | "property", key: string, content: string) {
  let el = document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${key}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute(attr, key);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

function setLink(rel: string, href: string) {
  let el = document.head.querySelector<HTMLLinkElement>(`link[rel="${rel}"]`);
  if (!el) {
    el = document.createElement("link");
    el.setAttribute("rel", rel);
    document.head.appendChild(el);
  }
  el.setAttribute("href", href);
}

function setJsonLd(id: string, data: Record<string, unknown>) {
  let el = document.getElementById(id) as HTMLScriptElement | null;
  if (!el) {
    el = document.createElement("script");
    el.id = id;
    el.type = "application/ld+json";
    document.head.appendChild(el);
  }
  el.textContent = JSON.stringify(data);
}

/**
 * Sets document-level SEO tags for the current route. Runs client-side, so
 * it primarily benefits JS-executing crawlers (Googlebot, and users who
 * navigate within the SPA and might share/bookmark a URL). Non-JS crawlers
 * get their meta tags from the pre-rendered static shells generated by
 * scripts/generate-static-routes.mjs at build time -- this hook keeps both
 * in sync since they read from the same routes.json.
 */
export function useSEO(options: SEOOptions) {
  useEffect(() => {
    const routeMeta = (siteConfig.routes as Record<string, { title: string; description: string }>)[
      options.path
    ];
    const title = options.title ?? routeMeta?.title ?? siteConfig.siteName;
    const description = options.description ?? routeMeta?.description ?? "";
    const url = `${SITE_URL}${options.path === "/" ? "/" : options.path + "/"}`;
    const image = `${SITE_URL}${siteConfig.defaultImage}`;

    document.title = title;
    setMeta("name", "description", description);
    setLink("canonical", url);

    // Open Graph
    setMeta("property", "og:type", "website");
    setMeta("property", "og:site_name", siteConfig.siteName);
    setMeta("property", "og:title", title);
    setMeta("property", "og:description", description);
    setMeta("property", "og:url", url);
    setMeta("property", "og:image", image);
    setMeta("property", "og:locale", siteConfig.locale);

    // Twitter Card
    setMeta("name", "twitter:card", "summary_large_image");
    setMeta("name", "twitter:title", title);
    setMeta("name", "twitter:description", description);
    setMeta("name", "twitter:image", image);
    if (siteConfig.twitterSite) {
      setMeta("name", "twitter:site", siteConfig.twitterSite);
    }

    // Default WebSite JSON-LD, always present
    setJsonLd("ld-website", {
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: siteConfig.siteName,
      url: SITE_URL,
      inLanguage: "fa",
      description: routeMeta?.description ?? description,
    });

    // Page-specific structured data (FAQPage, BreadcrumbList, etc.)
    const extraIds: string[] = [];
    options.structuredData?.forEach((data, i) => {
      const id = `ld-extra-${i}`;
      extraIds.push(id);
      setJsonLd(id, data);
    });

    // Clean up any stale extra JSON-LD blocks from a previous route that
    // had more structured data entries than this one.
    document.head
      .querySelectorAll('script[id^="ld-extra-"]')
      .forEach((el) => {
        if (!extraIds.includes(el.id)) el.remove();
      });
  }, [options.path, options.title, options.description, options.structuredData]);
}
